"""Shared compiler primitives and helpers for STM32 family compilers."""

from __future__ import annotations

import re
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar

from config import (
    ARM_AR,
    ARM_GCC,
    ARM_OBJCOPY,
    ARM_SIZE,
    BUILD_DIR,
    DEFAULT_CHIP,
    HAL_DIR,
    RTOS_DIR,
)

ChipInfo = dict[str, Any]


@dataclass(slots=True)
class CompileResult:
    """Result of a family-specific compilation step.

    `error_output` stores the most relevant compiler output. The compatibility
    facade uses it as the user-facing message for both success and failure.
    """

    success: bool
    bin_path: str | None
    bin_size: int
    error_output: str


def normalize_chip_name(chip: str | None) -> str:
    """Normalize a chip name for prefix matching and lookup."""
    return (chip or "").upper().replace("-", "").replace(" ", "")


def chip_to_pyocd_target(chip: str) -> str:
    """Convert `STM32F103C8T6` into the pyOCD target name `stm32f103c8`."""
    return re.sub(r"[a-z]\d$", "", chip.lower().strip())


def _default_chip_name() -> str:
    """Return the default chip name used as the last-resort fallback."""
    return normalize_chip_name(DEFAULT_CHIP) or "STM32F103C8"


def _find_freertos_root() -> Path | None:
    """Locate the FreeRTOS kernel root under the configured RTOS directory."""
    if not RTOS_DIR.exists():
        return None
    for directory in RTOS_DIR.iterdir():
        if directory.is_dir() and (directory / "tasks.c").exists():
            return directory
    return None


def _gen_freertos_config(chip_info: ChipInfo) -> str:
    """Generate a FreeRTOSConfig.h tuned for the selected chip."""
    cpu = chip_info["cpu"]
    ram_k = chip_info["ram_k"]
    has_fpu = chip_info.get("fpu", False)
    heap_b = min(ram_k * 1024 // 3, 32768)
    prio_bits = 4 if cpu in ("cortex-m3", "cortex-m4") else 2
    min_stack = 256 if has_fpu else 128
    has_dwt = cpu in ("cortex-m3", "cortex-m4")

    dwt_macros = ""
    if has_dwt:
        dwt_macros = """
/* DWT cycle counter for runtime stats (zero-cost hardware counter on Cortex-M3/M4) */
/* Use raw register addresses to avoid CMSIS header dependency */
#define portCONFIGURE_TIMER_FOR_RUN_TIME_STATS() do { \\
    (*(volatile uint32_t*)0xE000EDFC) |= (1UL << 24); /* DEMCR.TRCENA */ \\
    (*(volatile uint32_t*)0xE0001004) = 0;             /* DWT->CYCCNT = 0 */ \\
    (*(volatile uint32_t*)0xE0001000) |= 1;            /* DWT->CTRL.CYCCNTENA */ \\
} while(0)
#define portGET_RUN_TIME_COUNTER_VALUE() (*(volatile uint32_t*)0xE0001004)"""

    return f"""/* FreeRTOSConfig.h - Auto-generated by Gary Dev Agent */
#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#include <stdint.h>
extern uint32_t SystemCoreClock;

/* ---- Tick Type ---- */
#define configTICK_TYPE_WIDTH_IN_BITS           TICK_TYPE_WIDTH_32_BITS

/* ---- Scheduler ---- */
#define configUSE_PREEMPTION                    1
#define configUSE_TIME_SLICING                  1
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 0

/* ---- Clock ---- */
#define configCPU_CLOCK_HZ                      ( SystemCoreClock )
#define configTICK_RATE_HZ                      ( ( TickType_t ) 1000 )

/* ---- Tasks ---- */
#define configMAX_PRIORITIES                    ( 7 )
#define configMINIMAL_STACK_SIZE                ( ( uint16_t ) {min_stack} )
#define configMAX_TASK_NAME_LEN                 ( 16 )
#define configIDLE_SHOULD_YIELD                 1
#define configUSE_TASK_NOTIFICATIONS            1
#define configTASK_NOTIFICATION_ARRAY_ENTRIES   3

/* ---- Memory ---- */
#define configSUPPORT_STATIC_ALLOCATION         0
#define configSUPPORT_DYNAMIC_ALLOCATION        1
#define configTOTAL_HEAP_SIZE                   ( ( size_t )( {heap_b} ) )
#define configAPPLICATION_ALLOCATED_HEAP        0

/* ---- Hooks ---- */
/* vApplicationTickHook 内调用 HAL_IncTick()，维持 HAL 时基 */
#define configUSE_TICK_HOOK                     1
#define configUSE_IDLE_HOOK                     1
#define configUSE_MALLOC_FAILED_HOOK            1
#define configCHECK_FOR_STACK_OVERFLOW          2

/* ---- SW Timers ---- */
#define configUSE_TIMERS                        1
#define configTIMER_TASK_PRIORITY               ( configMAX_PRIORITIES - 1 )
#define configTIMER_QUEUE_LENGTH                8
#define configTIMER_TASK_STACK_DEPTH            ( configMINIMAL_STACK_SIZE * 2 )

/* ---- Sync primitives ---- */
#define configUSE_MUTEXES                       1
#define configUSE_RECURSIVE_MUTEXES             1
#define configUSE_COUNTING_SEMAPHORES           1
#define configUSE_QUEUE_SETS                    1
#define configQUEUE_REGISTRY_SIZE               8

/* ---- Stats / Trace / Debug ---- */
#define configGENERATE_RUN_TIME_STATS           {1 if has_dwt else 0}
#define configUSE_TRACE_FACILITY                1
#define configUSE_STATS_FORMATTING_FUNCTIONS    1
#define configRECORD_STACK_HIGH_ADDRESS          1
{dwt_macros}

/* ---- Co-routines ---- */
#define configUSE_CO_ROUTINES                   0

/* ---- Interrupt priorities (Cortex-M) ---- */
#define configLIBRARY_LOWEST_INTERRUPT_PRIORITY     15
#define configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY 5
#define configPRIO_BITS                              {prio_bits}
#define configKERNEL_INTERRUPT_PRIORITY  ( configLIBRARY_LOWEST_INTERRUPT_PRIORITY << ( 8 - configPRIO_BITS ) )
#define configMAX_SYSCALL_INTERRUPT_PRIORITY ( configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY << ( 8 - configPRIO_BITS ) )

/* ---- API includes ---- */
#define INCLUDE_vTaskPrioritySet                1
#define INCLUDE_uxTaskPriorityGet               1
#define INCLUDE_vTaskDelete                     1
#define INCLUDE_vTaskSuspend                    1
#define INCLUDE_xResumeFromISR                  1
#define INCLUDE_vTaskDelayUntil                 1
#define INCLUDE_vTaskDelay                      1
#define INCLUDE_xTaskGetSchedulerState          1
#define INCLUDE_xTaskGetCurrentTaskHandle       1
#define INCLUDE_uxTaskGetStackHighWaterMark     1
#define INCLUDE_xTaskGetIdleTaskHandle          1
#define INCLUDE_eTaskGetState                   1
#define INCLUDE_xTimerPendFunctionCall          1
#define INCLUDE_xTaskAbortDelay                 1
#define INCLUDE_xTaskGetHandle                  1

/* ---- Map FreeRTOS exception names to CMSIS/HAL names ---- */
#define xPortPendSVHandler  PendSV_Handler
#define xPortSysTickHandler SysTick_Handler
#define vPortSVCHandler     SVC_Handler

#endif /* FREERTOS_CONFIG_H */
"""


def _gen_linker_script_rtos(flash_k: int, ram_k: int) -> str:
    """Generate the RTOS linker script."""
    return f"""MEMORY {{
  FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = {flash_k}K
  RAM   (xrw) : ORIGIN = 0x20000000, LENGTH = {ram_k}K
}}
_estack = ORIGIN(RAM) + LENGTH(RAM);
_Min_Heap_Size  = 0x400;   /* 1 KB C heap（heap_4.c 内部独立维护，此处只占位） */
_Min_Stack_Size = 0x800;   /* 2 KB main/ISR stack（调度器启动前使用） */
SECTIONS {{
  .isr_vector : {{ KEEP(*(.isr_vector)) }} >FLASH
  .text : {{ *(.text*) *(.rodata*) . = ALIGN(4); _etext = .; }} >FLASH
  .init : {{ KEEP(*(.init)) }} >FLASH
  .fini : {{ KEEP(*(.fini)) }} >FLASH
  .init_array : {{ KEEP(*(.init_array*)) }} >FLASH
  .fini_array : {{ KEEP(*(.fini_array*)) }} >FLASH
  .data : AT(_etext) {{ _sdata = .; *(.data*) . = ALIGN(4); _edata = .; }} >RAM
  .bss : {{ _sbss = .; *(.bss*) *(COMMON) . = ALIGN(4); _ebss = .; end = _ebss; }} >RAM
  ._user_heap_stack : {{ . = ALIGN(8); . = . + _Min_Heap_Size; . = . + _Min_Stack_Size; . = ALIGN(8); }} >RAM
  /DISCARD/ : {{ *(.ARM.*) }}
}}
"""


CHIP_DB: dict[str, ChipInfo] = {
    "STM32F103C8": {
        "cpu": "cortex-m3",
        "flash_k": 64,
        "ram_k": 20,
        "define": "STM32F103xB",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103CB": {
        "cpu": "cortex-m3",
        "flash_k": 128,
        "ram_k": 20,
        "define": "STM32F103xB",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103RB": {
        "cpu": "cortex-m3",
        "flash_k": 128,
        "ram_k": 20,
        "define": "STM32F103xB",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103RC": {
        "cpu": "cortex-m3",
        "flash_k": 256,
        "ram_k": 48,
        "define": "STM32F103xE",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103RE": {
        "cpu": "cortex-m3",
        "flash_k": 512,
        "ram_k": 64,
        "define": "STM32F103xE",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103ZE": {
        "cpu": "cortex-m3",
        "flash_k": 512,
        "ram_k": 64,
        "define": "STM32F103xE",
        "family": "f1",
        "fpu": False,
    },
    "STM32F103VE": {
        "cpu": "cortex-m3",
        "flash_k": 512,
        "ram_k": 64,
        "define": "STM32F103xE",
        "family": "f1",
        "fpu": False,
    },
    "STM32F100RB": {
        "cpu": "cortex-m3",
        "flash_k": 128,
        "ram_k": 8,
        "define": "STM32F100xB",
        "family": "f1",
        "fpu": False,
    },
    "STM32F105": {
        "cpu": "cortex-m3",
        "flash_k": 256,
        "ram_k": 64,
        "define": "STM32F105xC",
        "family": "f1",
        "fpu": False,
    },
    "STM32F107": {
        "cpu": "cortex-m3",
        "flash_k": 256,
        "ram_k": 64,
        "define": "STM32F107xC",
        "family": "f1",
        "fpu": False,
    },
    "STM32F401CC": {
        "cpu": "cortex-m4",
        "flash_k": 256,
        "ram_k": 64,
        "define": "STM32F401xC",
        "family": "f4",
        "fpu": True,
    },
    "STM32F401CE": {
        "cpu": "cortex-m4",
        "flash_k": 512,
        "ram_k": 96,
        "define": "STM32F401xE",
        "family": "f4",
        "fpu": True,
    },
    "STM32F407VE": {
        "cpu": "cortex-m4",
        "flash_k": 512,
        "ram_k": 128,
        "define": "STM32F407xx",
        "family": "f4",
        "fpu": True,
    },
    "STM32F407VG": {
        "cpu": "cortex-m4",
        "flash_k": 1024,
        "ram_k": 128,
        "define": "STM32F407xx",
        "family": "f4",
        "fpu": True,
    },
    "STM32F407ZG": {
        "cpu": "cortex-m4",
        "flash_k": 1024,
        "ram_k": 128,
        "define": "STM32F407xx",
        "family": "f4",
        "fpu": True,
    },
    "STM32F411CE": {
        "cpu": "cortex-m4",
        "flash_k": 512,
        "ram_k": 128,
        "define": "STM32F411xE",
        "family": "f4",
        "fpu": True,
    },
    "STM32F429ZI": {
        "cpu": "cortex-m4",
        "flash_k": 2048,
        "ram_k": 256,
        "define": "STM32F429xx",
        "family": "f4",
        "fpu": True,
    },
    "STM32F446RE": {
        "cpu": "cortex-m4",
        "flash_k": 512,
        "ram_k": 128,
        "define": "STM32F446xx",
        "family": "f4",
        "fpu": True,
    },
    "STM32F030F4": {
        "cpu": "cortex-m0",
        "flash_k": 16,
        "ram_k": 4,
        "define": "STM32F030x6",
        "family": "f0",
        "fpu": False,
    },
    "STM32F030C8": {
        "cpu": "cortex-m0",
        "flash_k": 64,
        "ram_k": 8,
        "define": "STM32F030x8",
        "family": "f0",
        "fpu": False,
    },
    "STM32F072RB": {
        "cpu": "cortex-m0",
        "flash_k": 128,
        "ram_k": 16,
        "define": "STM32F072xB",
        "family": "f0",
        "fpu": False,
    },
    "STM32F303CC": {
        "cpu": "cortex-m4",
        "flash_k": 256,
        "ram_k": 40,
        "define": "STM32F303xC",
        "family": "f3",
        "fpu": True,
    },
    "STM32F303RE": {
        "cpu": "cortex-m4",
        "flash_k": 512,
        "ram_k": 64,
        "define": "STM32F303xE",
        "family": "f3",
        "fpu": True,
    },
}

_F1_IRQ_NAMES = [
    "WWDG_IRQHandler",
    "PVD_IRQHandler",
    "TAMPER_IRQHandler",
    "RTC_IRQHandler",
    "FLASH_IRQHandler",
    "RCC_IRQHandler",
    "EXTI0_IRQHandler",
    "EXTI1_IRQHandler",
    "EXTI2_IRQHandler",
    "EXTI3_IRQHandler",
    "EXTI4_IRQHandler",
    "DMA1_Channel1_IRQHandler",
    "DMA1_Channel2_IRQHandler",
    "DMA1_Channel3_IRQHandler",
    "DMA1_Channel4_IRQHandler",
    "DMA1_Channel5_IRQHandler",
    "DMA1_Channel6_IRQHandler",
    "DMA1_Channel7_IRQHandler",
    "ADC1_2_IRQHandler",
    "USB_HP_CAN1_TX_IRQHandler",
    "USB_LP_CAN1_RX0_IRQHandler",
    "CAN1_RX1_IRQHandler",
    "CAN1_SCE_IRQHandler",
    "EXTI9_5_IRQHandler",
    "TIM1_BRK_IRQHandler",
    "TIM1_UP_IRQHandler",
    "TIM1_TRG_COM_IRQHandler",
    "TIM1_CC_IRQHandler",
    "TIM2_IRQHandler",
    "TIM3_IRQHandler",
    "TIM4_IRQHandler",
    "I2C1_EV_IRQHandler",
    "I2C1_ER_IRQHandler",
    "I2C2_EV_IRQHandler",
    "I2C2_ER_IRQHandler",
    "SPI1_IRQHandler",
    "SPI2_IRQHandler",
    "USART1_IRQHandler",
    "USART2_IRQHandler",
    "USART3_IRQHandler",
    "EXTI15_10_IRQHandler",
    "RTC_Alarm_IRQHandler",
    "USBWakeUp_IRQHandler",
    "TIM8_BRK_IRQHandler",
    "TIM8_UP_IRQHandler",
    "TIM8_TRG_COM_IRQHandler",
    "TIM8_CC_IRQHandler",
    "ADC3_IRQHandler",
    "FSMC_IRQHandler",
    "SDIO_IRQHandler",
    "TIM5_IRQHandler",
    "SPI3_IRQHandler",
    "UART4_IRQHandler",
    "UART5_IRQHandler",
    "TIM6_IRQHandler",
    "TIM7_IRQHandler",
    "DMA2_Channel1_IRQHandler",
    "DMA2_Channel2_IRQHandler",
    "DMA2_Channel3_IRQHandler",
    "DMA2_Channel4_5_IRQHandler",
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
]

_F0_IRQ_NAMES = [
    "WWDG_IRQHandler",
    "PVD_VDDIO2_IRQHandler",
    "RTC_IRQHandler",
    "FLASH_IRQHandler",
    "RCC_CRS_IRQHandler",
    "EXTI0_1_IRQHandler",
    "EXTI2_3_IRQHandler",
    "EXTI4_15_IRQHandler",
    "TSC_IRQHandler",
    "DMA1_Channel1_IRQHandler",
    "DMA1_Channel2_3_IRQHandler",
    "DMA1_Channel4_5_6_7_IRQHandler",
    "ADC1_COMP_IRQHandler",
    "TIM1_BRK_UP_TRG_COM_IRQHandler",
    "TIM1_CC_IRQHandler",
    "TIM2_IRQHandler",
    "TIM3_IRQHandler",
    "TIM6_DAC_IRQHandler",
    "TIM7_IRQHandler",
    "TIM14_IRQHandler",
    "TIM15_IRQHandler",
    "TIM16_IRQHandler",
    "TIM17_IRQHandler",
    "I2C1_IRQHandler",
    "I2C2_IRQHandler",
    "SPI1_IRQHandler",
    "SPI2_IRQHandler",
    "USART1_IRQHandler",
    "USART2_IRQHandler",
    "USART3_4_IRQHandler",
    "CEC_CAN_IRQHandler",
    "USB_IRQHandler",
]

_F3_IRQ_NAMES = [
    "WWDG_IRQHandler",
    "PVD_IRQHandler",
    "TAMP_STAMP_IRQHandler",
    "RTC_WKUP_IRQHandler",
    "FLASH_IRQHandler",
    "RCC_IRQHandler",
    "EXTI0_IRQHandler",
    "EXTI1_IRQHandler",
    "EXTI2_TSC_IRQHandler",
    "EXTI3_IRQHandler",
    "EXTI4_IRQHandler",
    "DMA1_Channel1_IRQHandler",
    "DMA1_Channel2_IRQHandler",
    "DMA1_Channel3_IRQHandler",
    "DMA1_Channel4_IRQHandler",
    "DMA1_Channel5_IRQHandler",
    "DMA1_Channel6_IRQHandler",
    "DMA1_Channel7_IRQHandler",
    "ADC1_2_IRQHandler",
    "USB_HP_CAN1_TX_IRQHandler",
    "USB_LP_CAN1_RX0_IRQHandler",
    "CAN1_RX1_IRQHandler",
    "CAN1_SCE_IRQHandler",
    "EXTI9_5_IRQHandler",
    "TIM1_BRK_TIM15_IRQHandler",
    "TIM1_UP_TIM16_IRQHandler",
    "TIM1_TRG_COM_TIM17_IRQHandler",
    "TIM1_CC_IRQHandler",
    "TIM2_IRQHandler",
    "TIM3_IRQHandler",
    "TIM4_IRQHandler",
    "I2C1_EV_IRQHandler",
    "I2C1_ER_IRQHandler",
    "I2C2_EV_IRQHandler",
    "I2C2_ER_IRQHandler",
    "SPI1_IRQHandler",
    "SPI2_IRQHandler",
    "USART1_IRQHandler",
    "USART2_IRQHandler",
    "USART3_IRQHandler",
    "EXTI15_10_IRQHandler",
    "RTC_Alarm_IRQHandler",
    "USBWakeUp_IRQHandler",
    "TIM8_BRK_IRQHandler",
    "TIM8_UP_IRQHandler",
    "TIM8_TRG_COM_IRQHandler",
    "TIM8_CC_IRQHandler",
    "ADC3_IRQHandler",
    None,
    None,
    "SPI3_IRQHandler",
    "UART4_IRQHandler",
    "UART5_IRQHandler",
    "TIM6_DAC_IRQHandler",
    "TIM7_IRQHandler",
    "DMA2_Channel1_IRQHandler",
    "DMA2_Channel2_IRQHandler",
    "DMA2_Channel3_IRQHandler",
    "DMA2_Channel4_IRQHandler",
    "DMA2_Channel5_IRQHandler",
    "ADC4_IRQHandler",
    None,
    None,
    "COMP1_2_3_IRQHandler",
    "COMP4_5_6_IRQHandler",
    "COMP7_IRQHandler",
    None,
    None,
    None,
    None,
    None,
    "I2C3_EV_IRQHandler",
    "I2C3_ER_IRQHandler",
    "USB_HP_IRQHandler",
    "USB_LP_IRQHandler",
    "USBWakeUp_RMP_IRQHandler",
    "TIM20_BRK_IRQHandler",
    "TIM20_UP_IRQHandler",
    "TIM20_TRG_COM_IRQHandler",
    "TIM20_CC_IRQHandler",
    "FPU_IRQHandler",
    "SPI4_IRQHandler",
]

_F4_IRQ_NAMES = [
    "WWDG_IRQHandler",
    "PVD_IRQHandler",
    "TAMP_STAMP_IRQHandler",
    "RTC_WKUP_IRQHandler",
    "FLASH_IRQHandler",
    "RCC_IRQHandler",
    "EXTI0_IRQHandler",
    "EXTI1_IRQHandler",
    "EXTI2_IRQHandler",
    "EXTI3_IRQHandler",
    "EXTI4_IRQHandler",
    "DMA1_Stream0_IRQHandler",
    "DMA1_Stream1_IRQHandler",
    "DMA1_Stream2_IRQHandler",
    "DMA1_Stream3_IRQHandler",
    "DMA1_Stream4_IRQHandler",
    "DMA1_Stream5_IRQHandler",
    "DMA1_Stream6_IRQHandler",
    "ADC_IRQHandler",
    "CAN1_TX_IRQHandler",
    "CAN1_RX0_IRQHandler",
    "CAN1_RX1_IRQHandler",
    "CAN1_SCE_IRQHandler",
    "EXTI9_5_IRQHandler",
    "TIM1_BRK_TIM9_IRQHandler",
    "TIM1_UP_TIM10_IRQHandler",
    "TIM1_TRG_COM_TIM11_IRQHandler",
    "TIM1_CC_IRQHandler",
    "TIM2_IRQHandler",
    "TIM3_IRQHandler",
    "TIM4_IRQHandler",
    "I2C1_EV_IRQHandler",
    "I2C1_ER_IRQHandler",
    "I2C2_EV_IRQHandler",
    "I2C2_ER_IRQHandler",
    "SPI1_IRQHandler",
    "SPI2_IRQHandler",
    "USART1_IRQHandler",
    "USART2_IRQHandler",
    "USART3_IRQHandler",
    "EXTI15_10_IRQHandler",
    "RTC_Alarm_IRQHandler",
    "OTG_FS_WKUP_IRQHandler",
    "TIM8_BRK_TIM12_IRQHandler",
    "TIM8_UP_TIM13_IRQHandler",
    "TIM8_TRG_COM_TIM14_IRQHandler",
    "TIM8_CC_IRQHandler",
    "DMA1_Stream7_IRQHandler",
    "FSMC_IRQHandler",
    "SDIO_IRQHandler",
    "TIM5_IRQHandler",
    "SPI3_IRQHandler",
    "UART4_IRQHandler",
    "UART5_IRQHandler",
    "TIM6_DAC_IRQHandler",
    "TIM7_IRQHandler",
    "DMA2_Stream0_IRQHandler",
    "DMA2_Stream1_IRQHandler",
    "DMA2_Stream2_IRQHandler",
    "DMA2_Stream3_IRQHandler",
    "DMA2_Stream4_IRQHandler",
    "ETH_IRQHandler",
    "ETH_WKUP_IRQHandler",
    "CAN2_TX_IRQHandler",
    "CAN2_RX0_IRQHandler",
    "CAN2_RX1_IRQHandler",
    "CAN2_SCE_IRQHandler",
    "OTG_FS_IRQHandler",
    "DMA2_Stream5_IRQHandler",
    "DMA2_Stream6_IRQHandler",
    "DMA2_Stream7_IRQHandler",
    "USART6_IRQHandler",
    "I2C3_EV_IRQHandler",
    "I2C3_ER_IRQHandler",
    "OTG_HS_EP1_OUT_IRQHandler",
    "OTG_HS_EP1_IN_IRQHandler",
    "OTG_HS_WKUP_IRQHandler",
    "OTG_HS_IRQHandler",
    "DCMI_IRQHandler",
    None,
    "HASH_RNG_IRQHandler",
    "FPU_IRQHandler",
]

_FAMILY_IRQ_NAMES: dict[str, list[str | None]] = {
    "f0": _F0_IRQ_NAMES,
    "f1": _F1_IRQ_NAMES,
    "f3": _F3_IRQ_NAMES,
    "f4": _F4_IRQ_NAMES,
}

_FAMILY_HAL_FILES = {
    "f1": [
        "stm32f1xx_hal.c",
        "stm32f1xx_hal_cortex.c",
        "stm32f1xx_hal_rcc.c",
        "stm32f1xx_hal_rcc_ex.c",
        "stm32f1xx_hal_gpio.c",
        "stm32f1xx_hal_gpio_ex.c",
        "stm32f1xx_hal_uart.c",
        "stm32f1xx_hal_usart.c",
        "stm32f1xx_hal_tim.c",
        "stm32f1xx_hal_tim_ex.c",
        "stm32f1xx_hal_adc.c",
        "stm32f1xx_hal_adc_ex.c",
        "stm32f1xx_hal_i2c.c",
        "stm32f1xx_hal_dma.c",
        "stm32f1xx_hal_pwr.c",
        "stm32f1xx_hal_flash.c",
        "stm32f1xx_hal_flash_ex.c",
        "stm32f1xx_hal_exti.c",
        "stm32f1xx_hal_spi.c",
        "system_stm32f1xx.c",
    ],
    "f4": [
        "stm32f4xx_hal.c",
        "stm32f4xx_hal_cortex.c",
        "stm32f4xx_hal_rcc.c",
        "stm32f4xx_hal_rcc_ex.c",
        "stm32f4xx_hal_gpio.c",
        "stm32f4xx_hal_uart.c",
        "stm32f4xx_hal_usart.c",
        "stm32f4xx_hal_tim.c",
        "stm32f4xx_hal_tim_ex.c",
        "stm32f4xx_hal_adc.c",
        "stm32f4xx_hal_adc_ex.c",
        "stm32f4xx_hal_i2c.c",
        "stm32f4xx_hal_i2c_ex.c",
        "stm32f4xx_hal_dma.c",
        "stm32f4xx_hal_dma_ex.c",
        "stm32f4xx_hal_pwr.c",
        "stm32f4xx_hal_pwr_ex.c",
        "stm32f4xx_hal_flash.c",
        "stm32f4xx_hal_flash_ex.c",
        "stm32f4xx_hal_exti.c",
        "stm32f4xx_hal_spi.c",
        "stm32f4xx_hal_i2s.c",
        "stm32f4xx_hal_i2s_ex.c",
        "system_stm32f4xx.c",
    ],
    "f0": [
        "stm32f0xx_hal.c",
        "stm32f0xx_hal_cortex.c",
        "stm32f0xx_hal_rcc.c",
        "stm32f0xx_hal_rcc_ex.c",
        "stm32f0xx_hal_gpio.c",
        "stm32f0xx_hal_uart.c",
        "stm32f0xx_hal_usart.c",
        "stm32f0xx_hal_tim.c",
        "stm32f0xx_hal_tim_ex.c",
        "stm32f0xx_hal_adc.c",
        "stm32f0xx_hal_adc_ex.c",
        "stm32f0xx_hal_i2c.c",
        "stm32f0xx_hal_i2c_ex.c",
        "stm32f0xx_hal_dma.c",
        "stm32f0xx_hal_pwr.c",
        "stm32f0xx_hal_pwr_ex.c",
        "stm32f0xx_hal_flash.c",
        "stm32f0xx_hal_flash_ex.c",
        "stm32f0xx_hal_spi.c",
        "system_stm32f0xx.c",
    ],
    "f3": [
        "stm32f3xx_hal.c",
        "stm32f3xx_hal_cortex.c",
        "stm32f3xx_hal_rcc.c",
        "stm32f3xx_hal_rcc_ex.c",
        "stm32f3xx_hal_gpio.c",
        "stm32f3xx_hal_uart.c",
        "stm32f3xx_hal_usart.c",
        "stm32f3xx_hal_tim.c",
        "stm32f3xx_hal_tim_ex.c",
        "stm32f3xx_hal_adc.c",
        "stm32f3xx_hal_adc_ex.c",
        "stm32f3xx_hal_i2c.c",
        "stm32f3xx_hal_i2c_ex.c",
        "stm32f3xx_hal_dma.c",
        "stm32f3xx_hal_pwr.c",
        "stm32f3xx_hal_pwr_ex.c",
        "stm32f3xx_hal_flash.c",
        "stm32f3xx_hal_flash_ex.c",
        "stm32f3xx_hal_spi.c",
        "system_stm32f3xx.c",
    ],
}

_RTOS_PORT = {
    "f0": "ARM_CM0",
    "f1": "ARM_CM3",
    "f3": "ARM_CM4F",
    "f4": "ARM_CM4F",
}

_FREERTOS_CORE_FILES = [
    "tasks.c",
    "queue.c",
    "list.c",
    "timers.c",
    "event_groups.c",
    "stream_buffer.c",
]


def lookup_chip(chip_name: str | None) -> ChipInfo | None:
    """Look up chip metadata, supporting fuzzy package suffix matching."""
    name = normalize_chip_name(chip_name)
    if not name:
        return None
    if name in CHIP_DB:
        return dict(CHIP_DB[name])
    for suffix_len in range(2, 0, -1):
        key = name[:-suffix_len] if len(name) > suffix_len else name
        if key in CHIP_DB:
            return dict(CHIP_DB[key])
    for key, value in CHIP_DB.items():
        if name.startswith(key):
            return dict(value)
    match = re.match(r"(STM32[A-Z]\d{3})", name)
    if match:
        prefix = match.group(1)
        for key, value in CHIP_DB.items():
            if key.startswith(prefix):
                return dict(value)
    return None


def _gen_linker_script(flash_k: int, ram_k: int) -> str:
    """Generate the default bare-metal linker script."""
    return f"""MEMORY {{
  FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = {flash_k}K
  RAM   (xrw) : ORIGIN = 0x20000000, LENGTH = {ram_k}K
}}
_estack = ORIGIN(RAM) + LENGTH(RAM);
_Min_Heap_Size = 0x200;
_Min_Stack_Size = 0x400;
SECTIONS {{
  .isr_vector : {{ KEEP(*(.isr_vector)) }} >FLASH
  .text : {{ *(.text*) *(.rodata*) . = ALIGN(4); _etext = .; }} >FLASH
  .init : {{ KEEP(*(.init)) }} >FLASH
  .fini : {{ KEEP(*(.fini)) }} >FLASH
  .init_array : {{ KEEP(*(.init_array*)) }} >FLASH
  .fini_array : {{ KEEP(*(.fini_array*)) }} >FLASH
  .data : AT(_etext) {{ _sdata = .; *(.data*) . = ALIGN(4); _edata = .; }} >RAM
  .bss : {{ _sbss = .; *(.bss*) *(COMMON) . = ALIGN(4); _ebss = .; end = _ebss; }} >RAM
  ._user_heap_stack : {{ . = ALIGN(8); . = . + _Min_Heap_Size; . = . + _Min_Stack_Size; . = ALIGN(8); }} >RAM
  /DISCARD/ : {{ *(.ARM.*) }}
}}
"""


def _gen_startup(cpu: str, irq_names: list[str | None]) -> str:
    """Generate the startup assembly with weak aliases for all IRQs."""
    vec_lines = [f"  .word {name}" if name else "  .word 0  /* reserved */" for name in irq_names]
    weak_lines = [f".weak {name}\n.thumb_set {name}, Default_Handler" for name in irq_names if name]
    fpu_enable = ""
    if "m4" in cpu or "m7" in cpu:
        fpu_enable = """\
  @ Enable FPU - CPACR.CP10/CP11 full access (must be before any FPU instruction)
  ldr r0, =0xE000ED88
  ldr r1, [r0]
  orr r1, r1, #(0xF << 20)
  str r1, [r0]
  dsb
  isb"""
    dwt_enable = ""
    if "m3" in cpu or "m4" in cpu or "m7" in cpu:
        dwt_enable = """\
  @ Enable DWT cycle counter for FreeRTOS runtime stats
  ldr r0, =0xE000EDFC
  ldr r1, [r0]
  orr r1, r1, #(1 << 24)
  str r1, [r0]
  ldr r0, =0xE0001000
  ldr r1, [r0]
  orr r1, r1, #1
  str r1, [r0]"""
    vec_section = "\n".join(vec_lines)
    weak_section = "\n".join(weak_lines)
    return f""".syntax unified
.cpu {cpu}
.thumb

.global g_pfnVectors
.global Default_Handler

.section .isr_vector,"a",%progbits
.type g_pfnVectors, %object
g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word MemManage_Handler
  .word BusFault_Handler
  .word UsageFault_Handler
  .word 0,0,0,0
  .word SVC_Handler
  .word DebugMon_Handler
  .word 0
  .word PendSV_Handler
  .word SysTick_Handler
{vec_section}

.section .text.Reset_Handler
.weak Reset_Handler
.type Reset_Handler, %function
Reset_Handler:
  ldr r0, =_estack
  mov sp, r0
{fpu_enable}
{dwt_enable}
  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_etext
  b 2f
1: ldr r3, [r2], #4
  str r3, [r0], #4
2: cmp r0, r1
  blt 1b
  ldr r0, =_sbss
  ldr r1, =_ebss
  movs r2, #0
  b 4f
3: str r2, [r0], #4
4: cmp r0, r1
  blt 3b
  bl SystemInit
  bl main
  b .

.section .text.Default_Handler,"ax",%progbits
Default_Handler: b .

.weak NMI_Handler
.thumb_set NMI_Handler, Default_Handler
.weak HardFault_Handler
.thumb_set HardFault_Handler, Default_Handler
.weak MemManage_Handler
.thumb_set MemManage_Handler, Default_Handler
.weak BusFault_Handler
.thumb_set BusFault_Handler, Default_Handler
.weak UsageFault_Handler
.thumb_set UsageFault_Handler, Default_Handler
.weak SVC_Handler
.thumb_set SVC_Handler, Default_Handler
.weak DebugMon_Handler
.thumb_set DebugMon_Handler, Default_Handler
.weak PendSV_Handler
.thumb_set PendSV_Handler, Default_Handler
.weak SysTick_Handler
.thumb_set SysTick_Handler, Default_Handler
.weak SystemInit
.thumb_set SystemInit, Default_Handler
{weak_section}
"""


def _summarize_compiler_error(stderr: str) -> str:
    """Extract the most useful compiler and linker diagnostics."""
    lines = [
        line
        for line in stderr.split("\n")
        if any(
            token in line
            for token in (
                "error:",
                "undefined reference",
                "multiple definition",
                "cannot find",
                "No such file",
                "fatal:",
            )
        )
    ]
    lines = [line for line in lines if "collect2:" not in line] or lines
    return "\n".join(lines[:15]) if lines else stderr[:1000]


class ChipCompiler(ABC):
    """Abstract base class for chip-family compilers."""

    SUPPORTED_PREFIXES: ClassVar[list[str]] = []
    FAMILY: ClassVar[str] = ""

    def __init__(self) -> None:
        """Initialize shared compiler state."""
        self.has_gcc = False
        self.has_specs = False
        self.has_hal = False
        self.has_hal_lib = False
        self.hal_inc_dirs: list[str] = []
        self.hal_src_files: list[str] = []
        self._chip_info: ChipInfo | None = None
        self._current_family: str | None = None
        BUILD_DIR.mkdir(parents=True, exist_ok=True)

    @classmethod
    def supports(cls, chip: str) -> bool:
        """Return whether the compiler supports the provided chip prefix."""
        normalized = normalize_chip_name(chip)
        return any(normalized.startswith(prefix.upper()) for prefix in cls.SUPPORTED_PREFIXES)

    @abstractmethod
    def compile(self, source_path: str | Path, chip: str) -> CompileResult:
        """Compile a bare-metal source file for the selected chip."""

    @abstractmethod
    def get_flash_command(self, bin_path: str | Path, chip: str) -> list[str]:
        """Return the pyOCD flash command for the selected chip."""

    def compile_rtos(self, source_path: str | Path, chip: str) -> dict[str, Any]:
        """Compile a source file together with the FreeRTOS kernel."""
        source = Path(source_path)
        if not source.exists():
            return {"ok": False, "msg": f"源文件不存在: {source}", "bin_path": None, "bin_size": 0}

        chip_name = normalize_chip_name(chip) or _default_chip_name()
        self.set_chip(chip_name)
        self.check(chip_name)

        if self._chip_info is None:
            return {"ok": False, "msg": "芯片信息未初始化", "bin_path": None, "bin_size": 0}

        ci = self._chip_info
        family = self._current_family or self.FAMILY or ci.get("family", "f1")

        rtos_root = _find_freertos_root()
        if rtos_root is None:
            return {
                "ok": False,
                "msg": "FreeRTOS 内核未下载，请运行 python setup.py --rtos 下载",
                "bin_path": None,
                "bin_size": 0,
            }

        port_dir_name = _RTOS_PORT.get(family, "ARM_CM3")
        port_path = rtos_root / "portable" / "GCC" / port_dir_name
        heap_path = rtos_root / "portable" / "MemMang" / "heap_4.c"
        if not port_path.exists():
            return {
                "ok": False,
                "msg": f"FreeRTOS port 目录不存在: {port_path}",
                "bin_path": None,
                "bin_size": 0,
            }

        (BUILD_DIR / "FreeRTOSConfig.h").write_text(_gen_freertos_config(ci), encoding="utf-8")
        (BUILD_DIR / "link.ld").write_text(
            _gen_linker_script_rtos(ci["flash_k"], ci["ram_k"]),
            encoding="utf-8",
        )

        elf = BUILD_DIR / "firmware.elf"
        binf = BUILD_DIR / "firmware.bin"
        for path in (elf, binf):
            path.unlink(missing_ok=True)

        if not self.has_gcc:
            return {"ok": False, "msg": "arm-none-eabi-gcc 未安装", "bin_path": None, "bin_size": 0}

        cpu_flags = self._cpu_flags(ci)
        rtos_srcs: list[str] = []
        for filename in _FREERTOS_CORE_FILES:
            file_path = rtos_root / filename
            if file_path.exists():
                rtos_srcs.append(str(file_path))
        port_c = port_path / "port.c"
        if port_c.exists():
            rtos_srcs.append(str(port_c))
        if heap_path.exists():
            rtos_srcs.append(str(heap_path))

        rtos_inc_dirs = [str(rtos_root / "include"), str(port_path), str(BUILD_DIR)]
        all_inc = [f"-I{directory}" for directory in self.hal_inc_dirs + rtos_inc_dirs]

        if self.has_hal:
            if self.has_hal_lib:
                extra_srcs = rtos_srcs
                extra_libs = [f"-L{BUILD_DIR}", f"-lstm32hal_{family}"]
            else:
                extra_srcs = rtos_srcs + self.hal_src_files
                extra_libs = []

            cmd = [
                ARM_GCC,
                *cpu_flags,
                f"-D{ci['define']}",
                "-DUSE_HAL_DRIVER",
                *all_inc,
                "-Os",
                "-Wall",
                "-Wno-unused-variable",
                "-Wno-unused-function",
                "-ffunction-sections",
                "-fdata-sections",
                f"-T{BUILD_DIR / 'link.ld'}",
                "-Wl,--gc-sections",
                "-Wl,--print-memory-usage",
                str(source),
                str(BUILD_DIR / "startup.s"),
                *extra_srcs,
                "-o",
                str(elf),
                "-nostartfiles",
                *extra_libs,
                "-lc",
                "-lm",
                "-lnosys",
            ]
            if self.has_specs:
                cmd += ["--specs=nosys.specs", "--specs=nano.specs"]
        else:
            cmd = [
                ARM_GCC,
                *cpu_flags,
                f"-D{ci['define']}",
                *all_inc,
                "-fsyntax-only",
                "-Wall",
                str(source),
            ]

        source_text = source.read_text(encoding="utf-8")
        code_warnings: list[str] = []
        if "void SysTick_Handler" in source_text and "vApplicationTickHook" in source_text:
            code_warnings.append("⚠ 检测到自定义 SysTick_Handler，FreeRTOS 已接管 SysTick，请删除")
        if "HAL_Delay" in source_text:
            hal_delay_pos = source_text.find("HAL_Delay")
            xtask_pos = source_text.find("xTaskCreate")
            if hal_delay_pos >= 0 and xtask_pos >= 0 and hal_delay_pos < xtask_pos:
                code_warnings.append(
                    "⚠ HAL_Delay() 在 xTaskCreate() 之前调用，可能破坏 FreeRTOS 内部数据结构"
                )

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            if result.returncode == 0:
                if self.has_hal and elf.exists():
                    subprocess.run([ARM_OBJCOPY, "-O", "binary", str(elf), str(binf)], timeout=10)
                    size = binf.stat().st_size if binf.exists() else 0
                    mem_info = ""
                    try:
                        size_result = subprocess.run(
                            [ARM_SIZE, str(elf)],
                            capture_output=True,
                            text=True,
                            timeout=5,
                        )
                        if size_result.returncode == 0:
                            mem_info = size_result.stdout.strip()
                    except Exception:
                        mem_info = ""

                    mem_usage = ""
                    if result.stderr:
                        mem_lines = [
                            line
                            for line in result.stderr.split("\n")
                            if "Memory region" in line or "FLASH" in line or "RAM" in line
                        ]
                        if mem_lines:
                            mem_usage = "\n".join(mem_lines)

                    message = f"RTOS 编译成功 ({size}B)"
                    if mem_info:
                        message += f"\n{mem_info}"
                    if mem_usage:
                        message += f"\n{mem_usage}"
                    if code_warnings:
                        message += "\n" + "\n".join(code_warnings)
                    return {"ok": True, "msg": message, "bin_path": str(binf), "bin_size": size}
                return {"ok": True, "msg": "语法检查通过(无HAL)", "bin_path": None, "bin_size": 0}

            short = _summarize_compiler_error(result.stderr)
            if "SysTick_Handler" in short and "multiple definition" in short:
                short += "\n💡 FreeRTOS 已接管 SysTick_Handler，请删除自定义的 SysTick_Handler，改用 vApplicationTickHook"
            if "vApplicationTickHook" in short:
                short += "\n💡 configUSE_TICK_HOOK=1 需要定义 void vApplicationTickHook(void) { HAL_IncTick(); }"
            if "vApplicationIdleHook" in short:
                short += "\n💡 configUSE_IDLE_HOOK=1 需要定义 void vApplicationIdleHook(void) {}"
            if "vApplicationStackOverflowHook" in short:
                short += "\n💡 configCHECK_FOR_STACK_OVERFLOW=2 需要定义 void vApplicationStackOverflowHook(TaskHandle_t t, char *n) { while(1); }"
            if "vApplicationMallocFailedHook" in short:
                short += "\n💡 configUSE_MALLOC_FAILED_HOOK=1 需要定义 void vApplicationMallocFailedHook(void) { while(1); }"
            if code_warnings:
                short += "\n" + "\n".join(code_warnings)
            return {"ok": False, "msg": short, "bin_path": None, "bin_size": 0}
        except subprocess.TimeoutExpired:
            return {
                "ok": False,
                "msg": "RTOS 编译超时（FreeRTOS 源文件较多，请稍候重试）",
                "bin_path": None,
                "bin_size": 0,
            }
        except Exception as exc:
            return {"ok": False, "msg": str(exc), "bin_path": None, "bin_size": 0}

    def set_chip(self, chip_name: str) -> ChipInfo:
        """Set the active chip and regenerate linker/startup files."""
        info = lookup_chip(chip_name)
        if info is None:
            print(f"  ⚠️ 未知芯片 {chip_name}，使用默认 STM32F103C8 参数")
            info = dict(CHIP_DB["STM32F103C8"])
        self._chip_info = info

        (BUILD_DIR / "link.ld").write_text(
            _gen_linker_script(info["flash_k"], info["ram_k"]),
            encoding="utf-8",
        )
        irq_names = _FAMILY_IRQ_NAMES.get(info["family"], _F1_IRQ_NAMES)
        (BUILD_DIR / "startup.s").write_text(
            _gen_startup(info["cpu"], irq_names),
            encoding="utf-8",
        )

        if info["family"] != self._current_family:
            self._current_family = info["family"]
            self._find_hal(info["family"])
        return info

    def check(self, chip_name: str | None = None) -> dict[str, Any]:
        """Probe the local toolchain and HAL availability."""
        info: dict[str, Any] = {
            "gcc": False,
            "gcc_version": "",
            "specs": False,
            "hal": False,
            "chip_info": None,
        }

        requested_chip = normalize_chip_name(chip_name) or normalize_chip_name(DEFAULT_CHIP)
        if requested_chip:
            info["chip_info"] = self.set_chip(requested_chip)
        elif self._chip_info is None:
            info["chip_info"] = self.set_chip(_default_chip_name())

        try:
            result = subprocess.run(
                [ARM_GCC, "--version"], capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                self.has_gcc = True
                info["gcc"] = True
                info["gcc_version"] = result.stdout.split("\n")[0]
        except Exception:
            self.has_gcc = False

        cpu = self._chip_info["cpu"] if self._chip_info else "cortex-m3"
        if self.has_gcc:
            try:
                result = subprocess.run(
                    [
                        ARM_GCC,
                        f"-mcpu={cpu}",
                        "-mthumb",
                        "--specs=nosys.specs",
                        "--specs=nano.specs",
                        "-x",
                        "c",
                        "-E",
                        "-",
                        "-o",
                        "/dev/null",
                    ],
                    input="",
                    capture_output=True,
                    text=True,
                    timeout=5,
                )
                self.has_specs = result.returncode == 0
                info["specs"] = self.has_specs
            except Exception:
                self.has_specs = False

        info["hal"] = self.has_hal
        if self.has_hal and self.has_gcc:
            self.precompile_hal()
        info["hal_lib"] = self.has_hal_lib
        return info

    def precompile_hal(self) -> bool:
        """Precompile HAL sources into a static library for faster rebuilds."""
        if not self.has_hal or not self.has_gcc or not self._chip_info:
            return False

        family = self._current_family or self.FAMILY or "f1"
        lib_path = BUILD_DIR / f"libstm32hal_{family}.a"
        obj_dir = BUILD_DIR / f"hal_obj_{family}"
        obj_dir.mkdir(exist_ok=True)

        ci = self._chip_info
        cpu_flags = self._cpu_flags(ci)
        inc_flags = [f"-I{directory}" for directory in self.hal_inc_dirs]

        to_compile: list[tuple[Path, Path]] = []
        obj_files: list[Path] = []
        for src in self.hal_src_files:
            src_path = Path(src)
            obj = obj_dir / f"{src_path.stem}.o"
            obj_files.append(obj)
            if not obj.exists() or obj.stat().st_mtime < src_path.stat().st_mtime:
                to_compile.append((src_path, obj))

        if not to_compile and lib_path.exists():
            self.has_hal_lib = True
            return True

        total = len(self.hal_src_files)
        fresh = total - len(to_compile)
        print(f"  🔨 预编译 HAL ({len(to_compile)} 个/共 {total}，{fresh} 个复用缓存)...")

        for src_path, obj in to_compile:
            cmd = [
                ARM_GCC,
                *cpu_flags,
                f"-D{ci['define']}",
                "-DUSE_HAL_DRIVER",
                *inc_flags,
                "-Os",
                "-ffunction-sections",
                "-fdata-sections",
                "-c",
                str(src_path),
                "-o",
                str(obj),
            ]
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
                if result.returncode != 0:
                    first_err = result.stderr.split("\n")[0][:120]
                    print(f"  ❌ {src_path.name}: {first_err}")
                    return False
            except Exception as exc:
                print(f"  ❌ 预编译异常: {exc}")
                return False

        existing = [str(obj) for obj in obj_files if obj.exists()]
        if not existing:
            return False
        try:
            result = subprocess.run(
                [ARM_AR, "rcs", str(lib_path)] + existing,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode != 0:
                print(f"  ❌ ar 归档失败: {result.stderr[:100]}")
                return False
        except Exception as exc:
            print(f"  ❌ ar 异常: {exc}")
            return False

        size_kb = lib_path.stat().st_size // 1024
        print(f"  ✅ HAL 静态库已就绪: {lib_path.name} ({size_kb} KB)")
        self.has_hal_lib = True
        return True

    def _cpu_flags(self, chip_info: ChipInfo) -> list[str]:
        """Return CPU and FPU specific GCC flags."""
        cpu_flags = [f"-mcpu={chip_info['cpu']}", "-mthumb"]
        if chip_info["fpu"]:
            cpu_flags += ["-mfloat-abi=hard", "-mfpu=fpv4-sp-d16"]
        return cpu_flags

    def _build_flash_command(self, bin_path: str | Path, chip: str) -> list[str]:
        """Return the generic pyOCD flash command for a chip."""
        target = chip_to_pyocd_target(chip)
        return ["pyocd", "flash", str(bin_path), "-t", target]

    def _compile_baremetal(self, source_path: str | Path, chip: str) -> CompileResult:
        """Shared bare-metal compilation implementation used by family compilers."""
        source = Path(source_path)
        if not source.exists():
            return CompileResult(False, None, 0, f"源文件不存在: {source}")

        chip_name = normalize_chip_name(chip) or _default_chip_name()
        self.set_chip(chip_name)
        self.check(chip_name)

        if self._chip_info is None:
            return CompileResult(False, None, 0, "芯片信息未初始化")

        ci = self._chip_info
        elf = BUILD_DIR / "firmware.elf"
        binf = BUILD_DIR / "firmware.bin"
        for path in (elf, binf):
            path.unlink(missing_ok=True)

        if not self.has_gcc:
            return CompileResult(False, None, 0, "arm-none-eabi-gcc 未安装")

        cpu_flags = self._cpu_flags(ci)
        if self.has_hal:
            inc_flags = [f"-I{directory}" for directory in self.hal_inc_dirs]
            family = self._current_family or self.FAMILY or ci.get("family", "f1")
            if self.has_hal_lib:
                extra_srcs: list[str] = []
                extra_libs = [f"-L{BUILD_DIR}", f"-lstm32hal_{family}"]
            else:
                extra_srcs = self.hal_src_files
                extra_libs = []

            cmd = [
                ARM_GCC,
                *cpu_flags,
                f"-D{ci['define']}",
                "-DUSE_HAL_DRIVER",
                *inc_flags,
                "-Os",
                "-Wall",
                "-Wno-unused-variable",
                "-Wno-unused-function",
                "-ffunction-sections",
                "-fdata-sections",
                f"-T{BUILD_DIR / 'link.ld'}",
                "-Wl,--gc-sections",
                str(source),
                str(BUILD_DIR / "startup.s"),
                *extra_srcs,
                "-o",
                str(elf),
                "-nostartfiles",
                *extra_libs,
                "-lc",
                "-lm",
                "-lnosys",
            ]
            if self.has_specs:
                cmd += ["--specs=nosys.specs", "--specs=nano.specs"]
        else:
            cmd = [ARM_GCC, *cpu_flags, f"-D{ci['define']}", "-fsyntax-only", "-Wall", str(source)]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            if result.returncode == 0:
                if self.has_hal and elf.exists():
                    subprocess.run([ARM_OBJCOPY, "-O", "binary", str(elf), str(binf)], timeout=10)
                    size = binf.stat().st_size if binf.exists() else 0
                    return CompileResult(True, str(binf), size, f"编译成功 ({size}B)")
                return CompileResult(True, None, 0, "语法检查通过(无HAL)")
            return CompileResult(False, None, 0, _summarize_compiler_error(result.stderr))
        except subprocess.TimeoutExpired:
            return CompileResult(False, None, 0, "编译超时")
        except Exception as exc:
            return CompileResult(False, None, 0, str(exc))

    def _find_hal(self, family: str) -> None:
        """Locate HAL headers and sources for the requested family."""
        hal_header = f"stm32{family}xx_hal.h"
        self.has_hal_lib = False
        if not (HAL_DIR / "Inc" / hal_header).exists():
            self.has_hal = False
            self.hal_inc_dirs = []
            self.hal_src_files = []
            return

        self.has_hal = True
        self.hal_inc_dirs = [str(HAL_DIR / "Inc")]
        for path in (HAL_DIR / "CMSIS" / "Include", HAL_DIR / "CMSIS" / "Core" / "Include"):
            if path.exists():
                self.hal_inc_dirs.append(str(path))

        hal_src = HAL_DIR / "Src"
        needed = _FAMILY_HAL_FILES.get(family, [])
        self.hal_src_files = [
            str(hal_src / filename) for filename in needed if (hal_src / filename).exists()
        ]
